apiVersion: v1
kind: Namespace
metadata:
  name: tp-devops-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: tp-devops-dev
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: /home/elon/mysql
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: tp-devops-dev
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password
  namespace: tp-devops-dev
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: password
  # devops
  MYSQL_DATABASE: prueba
  # elon
  MYSQL_USER: ZWxvbg==
  # musk
  MYSQL_PASSWORD: bXVzaw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tp-devops-dev
  name: webapp-back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-back
  template:
    metadata:
      labels:
        app: webapp-back
    spec:
      containers:
        - image: leosebas065/tpidevopsdespuesvemospublic-back:dev
          imagePullPolicy: Always
          name: tpidevopsdespuesvemospublic-back
          env:
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: endpoints
                  key: DB_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: MYSQL_ROOT_PASSWORD
            - name: HOST_ENV
              valueFrom:
                configMapKeyRef:
                  name: endpoints
                  key: HOST_ENV
          ports:
            - containerPort: 9000
              name: webapp-back
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tp-devops-dev
  name: webapp-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp-front
  template:
    metadata:
      labels:
        app: webapp-front
    spec:
      containers:
        - image: leosebas065/tpidevopsdespuesvemospublic-front:dev
          imagePullPolicy: Always
          name: tpidevopsdespuesvemospublic-front
          ports:
            - containerPort: 3000
              name: webapp-front
---
apiVersion: v1
kind: Service
metadata:
  namespace: tp-devops-dev
  name: service-front
spec:
  type: ClusterIP
  selector:
    app: webapp-front
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: tp-devops-dev
  name: service-back
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    app: webapp-back
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tp-devops-dev
  name: endpoints
data:
  DB_PORT: '3306'
  HOST_ENV: 'dev'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: tp-devops-dev
  name: ingress-webapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /dev
spec:
  rules:
    - http:
        paths:
          - path: /dev/api
            pathType: Prefix
            backend:
              service:
                name: service-back
                port:
                  number: 9000
          - path: /dev
            pathType: Prefix
            backend:
              service:
                name: service-front
                port:
                  number: 3000